// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaaS_DAL.Data;

#nullable disable

namespace SaaS_DAL.Migrations
{
    [DbContext(typeof(SaaSDbContext))]
    [Migration("20260213224721_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SaaS_Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payment_method");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_price");

                    b.Property<int>("BillingInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("billing_interval");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PlanType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_type");

                    b.Property<int>("TrialDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trial_days");

                    b.HasKey("Id");

                    b.ToTable("plans");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.PlanAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddonName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("addon_name");

                    b.Property<int>("BillingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("billing_type");

                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("plan_addons");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_renew");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trial_end_date");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.SubscriptionAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_date");

                    b.Property<int>("PlanAddonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plan_addon_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanAddonId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_addons");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_role_id");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "role for managing things...",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Just a usual subscriber",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Payment", b =>
                {
                    b.HasOne("SaaS_Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.PlanAddon", b =>
                {
                    b.HasOne("SaaS_Domain.Entities.Plan", "Plan")
                        .WithMany("PlanAddons")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Subscription", b =>
                {
                    b.HasOne("SaaS_Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaS_Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.SubscriptionAddon", b =>
                {
                    b.HasOne("SaaS_Domain.Entities.PlanAddon", "PlanAddon")
                        .WithMany("SubscriptionAddons")
                        .HasForeignKey("PlanAddonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaS_Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionAddons")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAddon");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.User", b =>
                {
                    b.HasOne("SaaS_Domain.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanAddons");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.PlanAddon", b =>
                {
                    b.Navigation("SubscriptionAddons");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SubscriptionAddons");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.User", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SaaS_Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
